name: letterboxd-playground
channels:
  # https://anaconda.org/conda-forge
  - conda-forge
dependencies:
  - python=3.7.12
  - pip=22.0.2
  - jupyterlab=3.5.0
  - black-jupyter=22.10.0
  - pandas=1.3.4
